### ISSUE TITLE
Log Java Exception when running bal file

### ISSUE THREAD

**Issue by irunika** [ballerinalang/ballerina#1235]
There is a log of a java null point exception is shown when running a .bal file from
ServerConnectorMessagehandler : 112
Please look into it.

_Exception in thread "pool-2-thread-2" org.wso2.ballerina.core.exception.BallerinaException: org.wso2.ballerina.core.exception.BallerinaException: error in ballerina program: 
	at org.wso2.ballerina.core.runtime.errors.handler.DefaultServerConnectorErrorHandler.handleError(DefaultServerConnectorErrorHandler.java:44)
	at org.wso2.ballerina.core.runtime.ServerConnectorMessageHandler.handleError(ServerConnectorMessageHandler.java:125)
	at org.wso2.ballerina.core.runtime.ServerConnectorMessageHandler.handleInbound(ServerConnectorMessageHandler.java:96)
	at org.wso2.ballerina.core.runtime.threadpool.RequestWorkerThread.run(RequestWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.ballerina.core.exception.BallerinaException: error in ballerina program: 
	... 6 more_

**Comment by chanakaudaya** [comment]
@irunika Is this still valid?
