### ISSUE TITLE
[File Connector] [Bug]Java exceptions logged when deploying service with file connector

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#1944]
Built on: 118e02b84b24115145e07a8c74fcb31218b0655a
Please find the below observations with the attached bal code

1. When server started, following java exception occured
`Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: logs/carbon.log.lck
java.nio.file.NoSuchFileException: logs/carbon.log.lck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
	at java.util.logging.FileHandler.<init>(FileHandler.java:263)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.logging.LogManager$5.run(LogManager.java:966)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
	at java.util.logging.LogManager.access$1500(LogManager.java:145)
	at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
	at java.util.logging.Logger.getHandlers(Logger.java:1776)
	at java.util.logging.Logger.log(Logger.java:735)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.logp(Logger.java:930)
	at org.apache.commons.logging.impl.Jdk14Logger.log(Jdk14Logger.java:87)
	at org.apache.commons.logging.impl.Jdk14Logger.info(Jdk14Logger.java:176)
	at org.apache.commons.vfs2.VfsLog.info(VfsLog.java:139)
	at org.apache.commons.vfs2.impl.DefaultFileReplicator.init(DefaultFileReplicator.java:92)
	at org.apache.commons.vfs2.impl.PrivilegedFileReplicator$InitAction.run(PrivilegedFileReplicator.java:144)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.commons.vfs2.impl.PrivilegedFileReplicator.init(PrivilegedFileReplicator.java:93)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.setupComponent(DefaultFileSystemManager.java:435)
	at org.apache.commons.vfs2.impl.DefaultFileSystemManager.setReplicator(DefaultFileSystemManager.java:394)
	at org.apache.commons.vfs2.impl.StandardFileSystemManager.init(StandardFileSystemManager.java:101)
	at org.wso2.carbon.transport.file.connector.server.FileConsumer.<init>(FileConsumer.java:75)
	at org.wso2.carbon.transport.file.connector.server.FileServerConnector.start(FileServerConnector.java:65)
	at org.ballerinalang.services.dispatchers.file.FileServiceDispatcher.serviceRegistered(FileServiceDispatcher.java:90)
	at org.ballerinalang.BLangProgramRunner.lambda$startServices$124(BLangProgramRunner.java:61)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at org.ballerinalang.BLangProgramRunner.startServices(BLangProgramRunner.java:60)
	at org.ballerinalang.launcher.BProgramRunner.runServices(BProgramRunner.java:62)
	at org.ballerinalang.launcher.Main$RunServiceCmd.execute(Main.java:455)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:294)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:48)
`

[fileServer1.txt](https://github.com/ballerinalang/ballerina/files/782699/fileServer1.txt)

**Comment by sameera-jayasoma** [comment]
This is fixed now..
