### ISSUE TITLE
Showing java error messages with JMS MB sample

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1974]
Steps:
1. Follow the steps mention in [1] and setup the MB, ballerina server
[1] https://github.com/gvasanka/ballerina/blob/458308db57a7cd9361e58ad4bf7e2e5ec235e594/samples/other_samples/jmsServiceWithMB/README.txt#L22-L22

2. Deploy the ballerina service available on [2]
[2]https://github.com/gvasanka/ballerina/blob/master/samples/other_samples/jmsServiceWithMB/jmsWithMB.bal

3. Publish a map message from MB management console. Check the image
![selection_189](https://cloud.githubusercontent.com/assets/3368635/23093287/dcacd374-f604-11e6-8a56-b5a91202ab7e.png)

Issue:
Showing Java error message as per below on ballerina service console

error in ballerina program: given property queue message count is not found in the Map message
	 at ballerina.lang.messages:getStringValue(mbballerina.bal:15)
	 at onMessage(mbballerina.bal:11)
	 at jmsWSO2MBQueueService(mbballerina.bal:9)

Exception in thread "pool-9-thread-3" org.ballerinalang.util.exceptions.BallerinaException: Cannot handle error using the error handler for : jms
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleErrorInboundPath(ServerConnectorMessageHandler.java:135)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleInbound(ServerConnectorMessageHandler.java:100)
	at org.ballerinalang.runtime.threadpool.RequestWorkerThread.run(RequestWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
Caused by: org.ballerinalang.util.exceptions.BallerinaException: org.ballerinalang.util.exceptions.BallerinaException: error in ballerina program: given property queue message count is not found in the Map message
	at org.ballerinalang.services.DefaultServerConnectorErrorHandler.handleError(DefaultServerConnectorErrorHandler.java:45)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleErrorInboundPath(ServerConnectorMessageHandler.java:133)
	... 5 more
Caused by: org.ballerinalang.util.exceptions.BallerinaException: error in ballerina program: given property queue message count is not found in the Map message
	... 6 more

**Comment by Megala21** [comment]
This issues is fixed with https://github.com/wso2/carbon-transports/pull/207

**Comment by lankavitharana** [comment]
pull request merged, hence closing
