### ISSUE TITLE
Upgrade to Netty 4.1.9.final to resolve Mac address issue in Docker

### ISSUE THREAD

**Issue by chamilad** [ballerinalang/ballerina#1981]
`0.8.0-ALPHA` ships with Netty 4.1.7.final which has introduced a bug where the following stacktrace is produced when starting a Ballerina Service inside a Docker container. The root cause of the issue is that Netty prefers empty Mac address over a locally allocated Mac address (which Docker containers get) and is [already fixed](https://github.com/netty/netty/pull/6308) and targeted to be shipped with release 4.1.9.final. 

```
Running: ballerina run service /ballerina/files/workerservice.bsz
ballerina: deploying service(s) in '/ballerina/files/workerservice.bsz'
Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: logs/carbon.log.lck
java.nio.file.NoSuchFileException: logs/carbon.log.lck
at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
at java.nio.channels.FileChannel.open(FileChannel.java:287)
at java.nio.channels.FileChannel.open(FileChannel.java:335)
at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
at java.util.logging.FileHandler.(FileHandler.java:263)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at java.lang.Class.newInstance(Class.java:442)
at java.util.logging.LogManager$5.run(LogManager.java:966)
at java.security.AccessController.doPrivileged(Native Method)
at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
at java.util.logging.LogManager.access$1500(LogManager.java:145)
at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
at java.util.logging.Logger.getHandlers(Logger.java:1777)
at java.util.logging.Logger.log(Logger.java:735)
at io.netty.util.internal.logging.JdkLogger.log(JdkLogger.java:606)
at io.netty.util.internal.logging.JdkLogger.warn(JdkLogger.java:420)
at io.netty.util.internal.MacAddressUtil.defaultMachineId(MacAddressUtil.java:139)
at io.netty.channel.DefaultChannelId.(DefaultChannelId.java:100)
at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
at io.netty.channel.AbstractChannel.(AbstractChannel.java:79)
at io.netty.channel.nio.AbstractNioChannel.(AbstractNioChannel.java:84)
at io.netty.channel.nio.AbstractNioMessageChannel.(AbstractNioMessageChannel.java:42)
at io.netty.channel.socket.nio.NioServerSocketChannel.(NioServerSocketChannel.java:85)
at io.netty.channel.socket.nio.NioServerSocketChannel.(NioServerSocketChannel.java:71)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at java.lang.Class.newInstance(Class.java:442)
at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:319)
at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:281)
at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:277)
at org.wso2.carbon.transport.http.netty.listener.ServerConnectorController.bindInterface(ServerConnectorController.java:185)
at org.wso2.carbon.transport.http.netty.listener.HTTPServerConnector.start(HTTPServerConnector.java:54)
at org.ballerinalang.natives.connectors.BallerinaConnectorManager.startPendingConnectors(BallerinaConnectorManager.java:173)
at org.ballerinalang.launcher.BProgramRunner.runServices(BProgramRunner.java:67)
at org.ballerinalang.launcher.Main$RunServiceCmd.execute(Main.java:455)
at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:294)
at java.util.Optional.ifPresent(Optional.java:159)
at org.ballerinalang.launcher.Main.main(Main.java:48)
[2017-02-18 10:13:31,725] WARNING {io.netty.util.internal.MacAddressUtil defaultMachineId} - Failed to find a usable hardware address from the network interfaces; using random bytes: 8b:9b:0d:af:55:e9:06:29
ballerina: started server connector http-9090
```

**Comment by shafreenAnfar** [comment]
Updated netty to 4.1.16.final in Ballerina 0.95.1. Hence, closing the issue.
