### ISSUE TITLE
[JMS] ballerina service startup shows java errors if MB not available at that time

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#1992]
Steps:
1. Follow the steps mention in [1] and setup the MB, ballerina server
[1] https://github.com/gvasanka/ballerina/blob/458308db57a7cd9361e58ad4bf7e2e5ec235e594/samples/other_samples/jmsServiceWithMB/README.txt#L22-L22

2. Get the ballerina service available on [2]
[2]https://github.com/gvasanka/ballerina/blob/master/samples/other_samples/jmsServiceWithMB/jmsWithMB.bal

3. Run the ballerina code above and make sure ballerina service makes connection with WSO2 MB
4. Noe down the ballerina service and MB server
5. Try to start the ballerina service without starting MB server

Issue:
Shows following java messages, better to wrap with ballerina error

asankav@asankav-ThinkPad-T540p:~/servers/bal/ballerina-0.8.0-SNAPSHOT/bin$ ./ballerina run service /home/asankav/myarea/bal/Test/mbballerina.bal 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/asankav/servers/bal/ballerina-0.8.0-SNAPSHOT/bre/lib/slf4j-1.5.10.wso2v1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/asankav/servers/bal/ballerina-0.8.0-SNAPSHOT/bre/lib/slf4j-nop-1.7.22.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
ballerina: deploying service(s) in '/home/asankav/myarea/bal/Test/mbballerina.bal'
org.wso2.andes.AMQConnectionFailureException: Could not open connection
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:486)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:351)
	at org.wso2.andes.client.AMQConnectionFactory.createQueueConnection(AMQConnectionFactory.java:458)
	at org.wso2.carbon.transport.jms.factory.JMSConnectionFactory.createConnection(JMSConnectionFactory.java:268)
	at org.wso2.carbon.transport.jms.listener.JMSServerConnector.createMessageListener(JMSServerConnector.java:116)
	at org.wso2.carbon.transport.jms.listener.JMSServerConnector.start(JMSServerConnector.java:242)
	at org.ballerinalang.services.dispatchers.jms.JMSServiceDispatcher.serviceRegistered(JMSServiceDispatcher.java:93)
	at org.ballerinalang.BLangProgramRunner.lambda$startServices$0(BLangProgramRunner.java:61)
	at org.ballerinalang.BLangProgramRunner$$Lambda$149.0000000068C76830.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1291)
	at org.ballerinalang.BLangProgramRunner.startServices(BLangProgramRunner.java:60)
	at org.ballerinalang.launcher.BProgramRunner.runServices(BProgramRunner.java:62)
	at org.ballerinalang.launcher.Main$RunServiceCmd.execute(Main.java:455)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:294)
	at org.ballerinalang.launcher.Main$$Lambda$8.000000006880C1F0.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:170)
	at org.ballerinalang.launcher.Main.main(Main.java:48)
Caused by: org.wso2.andes.transport.TransportException: Could not open connection
	at org.wso2.andes.transport.network.mina.MinaNetworkTransport$IoConnectorCreator.connect(MinaNetworkTransport.java:216)
	at org.wso2.andes.transport.network.mina.MinaNetworkTransport.connect(MinaNetworkTransport.java:74)
	at org.wso2.andes.client.AMQConnectionDelegate_8_0.makeBrokerConnection(AMQConnectionDelegate_8_0.java:128)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:631)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:628)
	at java.security.AccessController.doPrivileged(AccessController.java:650)
	at org.wso2.andes.client.AMQConnection.makeBrokerConnection(AMQConnection.java:628)
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:409)
	... 16 more
org.wso2.andes.AMQConnectionFailureException: Could not open connection
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:486)
	at org.wso2.andes.client.AMQConnectionFactory.createConnection(AMQConnectionFactory.java:351)
	at org.wso2.andes.client.AMQConnectionFactory.createQueueConnection(AMQConnectionFactory.java:458)
	at org.wso2.carbon.transport.jms.factory.JMSConnectionFactory.createConnection(JMSConnectionFactory.java:268)
	at org.wso2.carbon.transport.jms.listener.JMSServerConnector.createMessageListener(JMSServerConnector.java:116)
	at org.wso2.carbon.transport.jms.listener.JMSConnectionRetryHandler.retry(JMSConnectionRetryHandler.java:79)
	at org.wso2.carbon.transport.jms.listener.JMSServerConnector.start(JMSServerConnector.java:254)
	at org.ballerinalang.services.dispatchers.jms.JMSServiceDispatcher.serviceRegistered(JMSServiceDispatcher.java:93)
	at org.ballerinalang.BLangProgramRunner.lambda$startServices$0(BLangProgramRunner.java:61)
	at org.ballerinalang.BLangProgramRunner$$Lambda$149.0000000068C76830.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1291)
	at org.ballerinalang.BLangProgramRunner.startServices(BLangProgramRunner.java:60)
	at org.ballerinalang.launcher.BProgramRunner.runServices(BProgramRunner.java:62)
	at org.ballerinalang.launcher.Main$RunServiceCmd.execute(Main.java:455)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:294)
	at org.ballerinalang.launcher.Main$$Lambda$8.000000006880C1F0.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:170)
	at org.ballerinalang.launcher.Main.main(Main.java:48)
Caused by: org.wso2.andes.transport.TransportException: Could not open connection
	at org.wso2.andes.transport.network.mina.MinaNetworkTransport$IoConnectorCreator.connect(MinaNetworkTransport.java:216)
	at org.wso2.andes.transport.network.mina.MinaNetworkTransport.connect(MinaNetworkTransport.java:74)
	at org.wso2.andes.client.AMQConnectionDelegate_8_0.makeBrokerConnection(AMQConnectionDelegate_8_0.java:128)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:631)
	at org.wso2.andes.client.AMQConnection$2.run(AMQConnection.java:628)
	at java.security.AccessController.doPrivileged(AccessController.java:650)
	at org.wso2.andes.client.AMQConnection.makeBrokerConnection(AMQConnection.java:628)
	at org.wso2.andes.client.AMQConnection.<init>(AMQConnection.java:409)
	... 17 more

**Comment by Megala21** [comment]
This issue cannot be handled by ballerina. Hence we can close this issue.

**Comment by sameera-jayasoma** [comment]
This is a known issue and it is clearly explained in the following issue.

https://github.com/ballerinalang/ballerina/issues/2789

We are closing this issue since the above issue is created track this.
