### ISSUE TITLE
[JMS] Sending incoming message directly as a Map Message to MB queue gives java errors

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#2005]
Steps:
1. Deploy the following ballerina code
2. Invoke the HTTP resource via client with empty message

Code:
```
import ballerina.net.jms;
import ballerina.lang.messages;
import ballerina.lang.system;

@http:BasePath ("/myService")
service jmsWSO2MBQueueSenderService {

  @http:POST
  @http:path ("/base")
    resource onMessage1 (message m) {
        system:println("Received message In Queue :::::::::"+ messages:getStringPayload(m));
        string messageType;
        map dataMap = {};
        messageType="MapMessage";
        jms:ClientConnector jmsEP = create jms:ClientConnector("org.wso2.andes.jndi.PropertiesFileInitialContextFactory", "jndi.properties");
        jms:ClientConnector.send(jmsEP, "QpidConnectionFactory", "ballerina", "queue", messageType, m, dataMap);

        reply m;
    }
}
```

Issue:
Getting following Java Error

asankav@asankav-ThinkPad-T540p:~/servers/bal/distri/ballerina-tools-0.8.0-SNAPSHOT/bin$ ./ballerina run service /home/asankav/myarea/bal/Test/jmssender.bal 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/asankav/servers/bal/distri/ballerina-tools-0.8.0-SNAPSHOT/bre/lib/slf4j-1.5.10.wso2v1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/asankav/servers/bal/distri/ballerina-tools-0.8.0-SNAPSHOT/bre/lib/slf4j-nop-1.7.22.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
ballerina: deploying service(s) in '/home/asankav/myarea/bal/Test/jmssender.bal'
Started listener http-9090
ballerina: started server connector org.wso2.carbon.transport.http.netty.listener.HTTPServerConnector@88b6cb80

Received message In Queue :::::::::
error in ballerina program: if the message type is MapMessage, either set MapData property or pass a received jms map message
	 at ballerina.net.jms:send(jmssender.bal:25)
	 at onMessage1(jmssender.bal:10)
	 at jmsWSO2MBQueueSenderService(jmssender.bal:6)

Exception in thread "pool-2-thread-1" java.lang.NoSuchMethodError: org/wso2/carbon/messaging/ServerConnectorErrorHandler.handleError(Ljava/lang/Exception;Lorg/wso2/carbon/messaging/CarbonMessage;Lorg/wso2/carbon/messaging/CarbonCallback;)V (loaded from file:/home/asankav/servers/bal/distri/ballerina-tools-0.8.0-SNAPSHOT/bre/lib/org.wso2.carbon.messaging-2.1.0.jar by sun.misc.Launcher$AppClassLoader@fbcad330) called from class org.ballerinalang.runtime.ServerConnectorMessageHandler (loaded from file:/home/asankav/servers/bal/distri/ballerina-tools-0.8.0-SNAPSHOT/bre/lib/ballerina-core-0.8.0-SNAPSHOT.jar by sun.misc.Launcher$AppClassLoader@fbcad330).
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleErrorInboundPath(ServerConnectorMessageHandler.java:133)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleInbound(ServerConnectorMessageHandler.java:100)
	at org.ballerinalang.runtime.threadpool.RequestWorkerThread.run(RequestWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)

**Comment by hasithaa** [comment]
Fixed with https://github.com/ballerinalang/ballerina/pull/2692.
