### ISSUE TITLE
Observing WARNING {org.apache.axiom.util.stax.dialect.StAXDialectDetector detectDialect}, When processing json messages 

### ISSUE THREAD

**Issue by gvasanka** [ballerinalang/ballerina#2042]
1. Deploy the below service

[stockQuoteRESTService.txt](https://github.com/ballerinalang/ballerina/files/786704/stockQuoteRESTService.txt)

2. Invoke the service with below payload
{
"market":"NYSE",
"symbol":"WSO2"
}
3. Check the stacktrace

Issue:
Observing following stacktrace

```
asankav@asankav-ThinkPad-T540p:~/Downloads/bal/ballerina-tools-0.8.0-SNAPSHOT/bin$ ./ballerina run service /home/asankav/svn/ballerina_test/services/artifacts/WrapSimpleStockQuoteAsREST/stockQuoteRESTService.bal 
ballerina: deploying service(s) in '/home/asankav/svn/ballerina_test/services/artifacts/WrapSimpleStockQuoteAsREST/stockQuoteRESTService.bal'
ballerina: started server connector http-9090

Can't load log handler "java.util.logging.FileHandler"
java.nio.file.NoSuchFileException: logs/carbon.log.lck
java.nio.file.NoSuchFileException: logs/carbon.log.lck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:459)
	at java.util.logging.FileHandler.<init>(FileHandler.java:263)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.logging.LogManager$5.run(LogManager.java:966)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
	at java.util.logging.LogManager.access$1500(LogManager.java:145)
	at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
	at java.util.logging.Logger.getHandlers(Logger.java:1776)
	at java.util.logging.Logger.log(Logger.java:735)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.logp(Logger.java:930)
	at org.apache.commons.logging.impl.Jdk14Logger.log(Jdk14Logger.java:87)
	at org.apache.commons.logging.impl.Jdk14Logger.warn(Jdk14Logger.java:260)
	at org.apache.axiom.util.stax.dialect.StAXDialectDetector.detectDialect(StAXDialectDetector.java:214)
	at org.apache.axiom.util.stax.dialect.StAXDialectDetector.getDialect(StAXDialectDetector.java:199)
	at org.apache.axiom.util.stax.dialect.StAXDialectDetector.getDialect(StAXDialectDetector.java:163)
	at org.apache.axiom.util.stax.dialect.StAXDialectDetector.getDialect(StAXDialectDetector.java:177)
	at org.apache.axiom.om.util.StAXUtils$1.run(StAXUtils.java:447)
	at org.apache.axiom.om.util.StAXUtils$1.run(StAXUtils.java:425)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.axiom.om.util.StAXUtils.newXMLInputFactory(StAXUtils.java:425)
	at org.apache.axiom.om.util.StAXUtils.getXMLInputFactory_perClassLoader(StAXUtils.java:495)
	at org.apache.axiom.om.util.StAXUtils.getXMLInputFactory(StAXUtils.java:168)
	at org.apache.axiom.om.util.StAXUtils.getXMLInputFactory(StAXUtils.java:133)
	at org.apache.axiom.om.util.StAXUtils.createXMLStreamReader(StAXUtils.java:234)
	at org.apache.axiom.om.impl.common.factory.AbstractOMMetaFactory.createXMLStreamReader(AbstractOMMetaFactory.java:126)
	at org.apache.axiom.om.impl.common.factory.AbstractOMMetaFactory.createOMBuilder(AbstractOMMetaFactory.java:167)
	at org.apache.axiom.om.OMXMLBuilderFactory.createOMBuilder(OMXMLBuilderFactory.java:290)
	at org.apache.axiom.om.OMXMLBuilderFactory.createOMBuilder(OMXMLBuilderFactory.java:274)
	at org.apache.axiom.om.util.AXIOMUtil.stringToOM(AXIOMUtil.java:54)
	at org.apache.axiom.om.util.AXIOMUtil.stringToOM(AXIOMUtil.java:39)
	at org.ballerinalang.model.values.BXML.<init>(BXML.java:46)
	at org.ballerinalang.bre.BLangExecutor.visit(BLangExecutor.java:857)
	at org.ballerinalang.model.expressions.BacktickExpr.execute(BacktickExpr.java:53)
	at org.ballerinalang.bre.BLangExecutor.visit(BLangExecutor.java:182)
	at org.ballerinalang.model.statements.AssignStmt.execute(AssignStmt.java:60)
	at org.ballerinalang.bre.BLangExecutor.visit(BLangExecutor.java:138)
	at org.ballerinalang.model.statements.BlockStmt.execute(BlockStmt.java:64)
	at org.ballerinalang.bre.BLangExecutor.visit(BLangExecutor.java:692)
	at org.ballerinalang.model.expressions.ResourceInvocationExpr.executeMultiReturn(ResourceInvocationExpr.java:57)
	at org.ballerinalang.runtime.BalProgramExecutor.execute(BalProgramExecutor.java:140)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleInbound(ServerConnectorMessageHandler.java:97)
	at org.ballerinalang.runtime.threadpool.RequestWorkerThread.run(RequestWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-02-20 11:44:24,714]  WARNING {org.apache.axiom.util.stax.dialect.StAXDialectDetector detectDialect} - Unable to determine dialect of the StAX implementation at jar:file:/home/asankav/Downloads/bal/ballerina-tools-0.8.0-SNAPSHOT/bre/lib/swagger-ballerina-generator-0.8.0.jar!/ 

```

**Comment by chanakaudaya** [comment]
Fixed with 0.8.0 GA.
