### ISSUE TITLE
Ballerina file deployer : skip .swp files 

### ISSUE THREAD

**Issue by kasun04** [ballerinalang/ballerina#213]
Error logs when a given bal file is opened by another application while the Ballerina runs in the server mode. 

[2016-12-12 12:51:21,576] ERROR {org.wso2.carbon.deployment.engine.internal.DeploymentEngine} - Error while updating artifact org.wso2.carbon.deployment.engine.exception.CarbonDeploymentException: Deployed artifact key is null for : .echoService.bal.swp
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$updateArtifacts$2(DeploymentEngine.java:323)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.updateArtifacts(DeploymentEngine.java:308)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:96)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.SchedulerTask.run(SchedulerTask.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by SupunS** [comment]
This issue no longer exists (in v0.8.0).
