### ISSUE TITLE
Array doesn't grow beyond 2000 

### ISSUE THREAD

**Issue by nihlaakram** [ballerinalang/ballerina#2456]
code
 `import ballerina.lang.system;
import ballerina.lang.arrays;

function main (string[] args) {
    int [] arr = [];
    arr[2000] =0;
    system:println(arrays:length(arr));
}`

error message
`error in ballerina program: 20
	 at main(ArraySizeTest.bal:4)`

stack trace
`java.lang.ArrayIndexOutOfBoundsException: 20
        at org.ballerinalang.model.values.BArray.grow(BArray.java:173)
        at org.ballerinalang.model.values.BArray.ensureCapacity(BArray.java:155)
        at org.ballerinalang.model.values.BArray.add(BArray.java:72)
        at org.ballerinalang.bre.BLangExecutor.assignValueToArrayMapAccessExpr(BLangExecutor.java:1246)
        at org.ballerinalang.bre.BLangExecutor.assignValueToFieldAccessExpr(BLangExecutor.java:1359)
        at org.ballerinalang.bre.BLangExecutor.visit(BLangExecutor.java:214)
        at org.ballerinalang.model.statements.AssignStmt.execute(AssignStmt.java:60)
        at org.ballerinalang.bre.BLangExecutor.visit(BLangExecutor.java:162)
        at org.ballerinalang.model.statements.BlockStmt.execute(BlockStmt.java:64)
        at org.ballerinalang.BLangProgramRunner.runMain(BLangProgramRunner.java:146)
        at org.ballerinalang.launcher.BProgramRunner.runMain(BProgramRunner.java:50)
        at org.ballerinalang.launcher.Main$RunMainCmd.execute(Main.java:287)
        at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:218)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.ballerinalang.launcher.Main.main(Main.java:52)
error in ballerina program: 20
         at main(ArraySizeTest.bal:4)
`

**Comment by SupunS** [comment]
Works fine in v0.91

Sample:
```go
function main (string[] args) {
  int [] arr = [];
  arr[5000000] = 0;
  system:println(lengthof arr);
}
```
