### ISSUE TITLE
Complex type mapping does not work and throws a nullPointerException

### ISSUE THREAD

**Issue by dilinisg** [ballerinalang/ballerina#2504]
1. Execute the below program
```
import ballerina.lang.system;
import ballerina.lang.messages;

struct Person {
    string first_name;
    string last_name;
    int age;
    float marks;
    json family;
    xml books;
    map properties;
    any comment;
    message msg;
    boolean isMarried;
    int[] arrNum;
    Address address;
}

struct Employee {
    string fname;
    string lname;
    int age;
    float marks;
    json family;
    xml books;
    map props;
    any comment;
    message msg;
    boolean isMarried;
    int[] arrNum;
    Location location;
}

struct Address {
    int num;
    string city;

}

struct Location {
    int number;
    string city;
    string country;

}

function main (string[] args) {

    system:println("Hello, World!");
    string lname;
    string fname;
    int age;
    float marks;
    json family;
    xml books;
    map props;
    any comment;
    message msg;
    boolean isMarried;
    int[] arrNum;
    Location location;


    fname, lname, age, marks, family, books, props, comment, msg, isMarried, arrNum, location = oneToOneTransform();
    system:println("First name - " + fname);
    system:println("Last name - " + lname);
    system:println("Age - " + age);

}


function oneToOneTransform () (string, string, int, float, json, xml, map, any, message, boolean, int[], Location){
    xml book = `<book>
                    <title lang="en">Harry Potter</title>
                    <author>J K. Rowling</author>
                    <year>2005</year>
                    <price>29.99</price>
                </book>`;

    message m = {};
    messages:setStringPayload(m,"this is a message");

    string s = "hello";
    any a = s;
    system:println(a);
    system:println("&&&&&&&&&&&");
    Person p = {first_name:"John", comment:"This is any type", last_name:"Doe", age:30, marks:90.67,
               family:{father:"Deamon", mother:"Elena"},
               books:book, properties:{"username":"root", "password":"root"}, msg:m, isMarried:true,
               address:{num:20, city:"Colombo"}, arrNum:[1,2,3]};
    Employee e = {};
    e.location.number = p.address.num;

    transform {
        e.fname = p.first_name;
        e.lname = p.last_name;
        e.age = p.age;
        e.marks = p.marks;
        e.family = p.family;
        e.books = p.books;
        e.props = p.properties;
        e.comment = p.comment;
        e.msg = p.msg;
        e.isMarried = p.isMarried;
        e.arrNum = p.arrNum;

    }

    system:println("-----------");
    return e.fname, e.lname, e.age, e.marks, e.family, e.books, e.props, e.comment, e.msg, e.isMarried, e.arrNum, e.location;
}
```

**Issue**
"ballerina: unexpected error occurred" error is thrown to the user. The following NullPointerException is logged. This happens when the following mapping is done.
**e.location.number = p.address.num;**

```
[2017-06-07 16:52:45,558]  SEVERE {org.ballerinalang.launcher.Main main} - ballerina: unexpected error occurred 
java.lang.NullPointerException
	at org.ballerinalang.bre.bvm.BLangVM.exec(BLangVM.java:509)
	at org.ballerinalang.bre.bvm.BLangVM.run(BLangVM.java:155)
	at org.ballerinalang.BLangProgramRunner.runMain(BLangProgramRunner.java:175)
	at org.ballerinalang.launcher.BProgramRunner.runMain(BProgramRunner.java:49)
	at org.ballerinalang.launcher.Main$RunMainCmd.execute(Main.java:287)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:218)
	at org.ballerinalang.launcher.Main$$Lambda$9/1297685781.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:52)

```

**Comment by SupunS** [comment]
Tested with v0.91.1-SNAPSHOT. Gives a proper error indicating the null:
```
error: ballerina.lang.errors:NullReferenceError
	at .:oneToOneTransform(mainFunction.bal:93)
	at .:main(mainFunction.bal:51)
```
