### ISSUE TITLE
Handle the "ballerina.lang.errors:Error, message: failed to send the request through the default pooling"

### ISSUE THREAD

**Issue by erandidesilva** [ballerinalang/ballerina#2936]
For the following Bre.log, $subject occurs at the console. Ideally this should be handled and a proper message should be given to the client. In this instance, it's connection refused.

```
[2017-07-19 16:56:40,139]  ERROR {org.wso2.carbon.transport.http.netty.sender.channel.pool.ConnectionManager} - Failed to send the request through the default pooling 
java.net.ConnectException: Connection refused, localhost-5300
	at org.wso2.carbon.transport.http.netty.sender.channel.ChannelUtils.openChannel(ChannelUtils.java:119)
	at org.wso2.carbon.transport.http.netty.sender.channel.pool.PoolableTargetChannelFactory.makeObject(PoolableTargetChannelFactory.java:56)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.wso2.carbon.transport.http.netty.sender.channel.pool.ConnectionManager.executeTargetChannel(ConnectionManager.java:176)
	at org.wso2.carbon.transport.http.netty.sender.HTTPClientConnector.send(HTTPClientConnector.java:137)
	at org.ballerinalang.nativeimpl.actions.http.AbstractHTTPAction.executeNonBlockingAction(AbstractHTTPAction.java:193)
	at org.ballerinalang.nativeimpl.actions.http.Get.execute(Get.java:92)
	at org.ballerinalang.bre.bvm.BLangVM.invokeNativeAction(BLangVM.java:2583)
	at org.ballerinalang.bre.bvm.BLangVM.exec(BLangVM.java:1232)
	at org.ballerinalang.bre.bvm.BLangVM.run(BLangVM.java:186)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.invokeResource(ServerConnectorMessageHandler.java:238)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleInbound(ServerConnectorMessageHandler.java:96)
	at org.ballerinalang.runtime.threadpool.RequestWorkerThread.run(RequestWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5300
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:346)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:630)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	... 1 more
```

**Comment by shafreenAnfar** [comment]
This has been fixed in the latest release. A relevant error message is printed when something like above happens.
