### ISSUE TITLE
Can't set attachment points to Annotations

### ISSUE THREAD

**Issue by manuranga** [ballerinalang/ballerina#2939]
```
Uncaught TypeError: this.props.onSuggestionSelected is not a function
    at SuggestionsText.value (http://localhost:9091/dist/bundle.js:29:173894)
    at Autosuggest.onSuggestionSelected (http://localhost:9091/dist/bundle.js:154:213580)
    at Object.onSuggestionClick [as onClick] (http://localhost:9091/dist/bundle.js:154:214007)
    at Item.n.onClick (http://localhost:9091/dist/bundle.js:154:227161)
    at Object.invokeGuardedCallback (http://localhost:9091/dist/bundle.js:37:17545)
    at executeDispatch (http://localhost:9091/dist/bundle.js:37:13092)
    at Object.executeDispatchesInOrder (http://localhost:9091/dist/bundle.js:37:13344)
    at M (http://localhost:9091/dist/bundle.js:29:182105)
    at d (http://localhost:9091/dist/bundle.js:29:182231)
    at Array.forEach (native)
```

**Comment by manuranga** [comment]
moved to https://github.com/ballerinalang/composer/issues/2458
