### ISSUE TITLE
When debugging a certain point an error occurs

### ISSUE THREAD

**Issue by stelanbriyan** [ballerinalang/ballerina#3014]
Web service is already up but when debugging and calling from postman, and error occurs saying : "Unexpected internal error near index 1
\
 ^
"

This issue occurs only in the debug mode.

`    
@http:POST {}
    @http:Path {value:"/createNewTicket"}
    resource createNewTicket (message m) {
        json ticketJson = messages:getJsonPayload(m);
        string ticketString = jsons:toString(ticketJson);
        domain:Ticket t;
        errors:TypeConversionError e;
        t, e = <domain:Ticket>ticketJson;

        system:println(t.username);
        reply m;
    }

`

Postman JSON:

{
	"username":"foo",
	"startLocation":"10",
	"endLocation":"20"
}

error log 

[2017-07-22 12:52:44,024]  ERROR {org.ballerinalang.runtime.ServerConnectorMessageHandler} - error: Unexpected internal error near index 1
\
 ^ 
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.compile(Pattern.java:1702)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.split(String.java:2380)
	at java.lang.String.split(String.java:2422)
	at org.ballerinalang.util.debugger.DebugInfoHolder$DebuggerPkgInfo.addLineNumberInfo(DebugInfoHolder.java:225)
	at org.ballerinalang.util.debugger.DebugInfoHolder.processPkgInfo(DebugInfoHolder.java:84)
	at org.ballerinalang.util.debugger.DebugInfoHolder.lambda$init$19(DebugInfoHolder.java:56)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.ballerinalang.util.debugger.DebugInfoHolder.init(DebugInfoHolder.java:56)
	at org.ballerinalang.bre.Context.setAndInitDebugInfoHolder(Context.java:88)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.invokeResource(ServerConnectorMessageHandler.java:233)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleInbound(ServerConnectorMessageHandler.java:97)
	at org.ballerinalang.runtime.threadpool.RequestWorkerThread.run(RequestWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
 
[2017-07-22 12:52:44,037]  ERROR {org.ballerinalang.services.dispatchers.http.HTTPErrorHandler} - Unexpected internal error near index 1
\
 ^

**Comment by lankavitharana** [comment]
I tried reproducing this, but it works fine for me, it would be great if you can provide the full sample code.

**Comment by SupunS** [comment]
Closing the issue, as per the above comment.
Please do reopen if the issue still persists.
