### ISSUE TITLE
BVM crashes when HTTP methods are not enclosed in quotes

### ISSUE THREAD

**Issue by pubudu91** [ballerinalang/ballerina#3266]
Consider the following sample program:
```
import ballerina.net.http;

@http:configuration{basePath: "/chuck"}
service<http> chuck {
    http:ClientConnector chuckService = create http:ClientConnector("https://api.chucknorris.io");

    @http:resourceConfig {
        path: "/",
        methods: [GET]
    }
    resource chuckJokes(message m) {
        message response = chuckService.get("/jokes/random", m);
        reply response;
    }
}
```
Note how `GET` is defined in methods: it's defined as GET as opposed to "GET" (the correct usage). This causes the BVM to crash and there is no indication to the user as to why this happened. Ideally, this should give a descriptive error to the user as to why the program didn't run. There isn't anything useful on the `bre.log` either as to why the VM crashed. It just shows a null pointer exception. The log from `bre.log` is given below:
```
[2017-08-31 11:29:14,539]  ERROR {org.ballerinalang.launcher.Main} - ballerina: internal error occurred 
java.lang.NullPointerException
	at org.ballerinalang.util.semantics.SemanticAnalyzer.lambda$validateAttributes$1(SemanticAnalyzer.java:868)
	at java.util.HashMap.forEach(HashMap.java:1288)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.validateAttributes(SemanticAnalyzer.java:828)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:815)
	at org.ballerinalang.model.AnnotationAttachment.accept(AnnotationAttachment.java:103)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:424)
	at org.ballerinalang.model.Resource.accept(Resource.java:236)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:351)
	at org.ballerinalang.model.Service.accept(Service.java:129)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:266)
	at org.ballerinalang.model.BLangPackage.accept(BLangPackage.java:283)
	at org.ballerinalang.util.semantics.SemanticAnalyzer.visit(SemanticAnalyzer.java:209)
	at org.ballerinalang.model.BLangProgram.accept(BLangProgram.java:133)
	at org.ballerinalang.BLangCompiler.compile(BLangCompiler.java:71)
	at org.ballerinalang.launcher.LauncherUtils.runProgram(LauncherUtils.java:61)
	at org.ballerinalang.launcher.Main$RunCmd.execute(Main.java:260)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.launcher.Main.main(Main.java:61)
```

**Comment by pubudu91** [comment]
This is correctly handled now and is detected as a compile error
