### ISSUE TITLE
[HTTP] Ballerina Hangs when serving http requests

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3270]
**Steps to Reproduce**

1. Send following combination of requests.

  | Payload Size | TPS
-- | -- | --
HTTP Payloads | 1K | 15
  | 5K | 10
  | 10K | 7
  | 100K | 5
  | 500K | 2

**Issue :** After sometimes ballerina stops serving messages and doesn't recover.

According to the thread dump following threads are waiting,

```
"BLangWorker-447" #477 prio=5 os_prio=0 tid=0x00007fd6dc01a800 nid=0xcf1 in Object.wait() [0x00007fd65d2d1000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000ee511b78> (a io.netty.bootstrap.AbstractBootstrap$PendingRegistrationPromise)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:254)
	- locked <0x00000000ee511b78> (a io.netty.bootstrap.AbstractBootstrap$PendingRegistrationPromise)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28)
	at org.wso2.carbon.transport.http.netty.sender.channel.ChannelUtils.openChannel(ChannelUtils.java:109)
	at org.wso2.carbon.transport.http.netty.sender.channel.pool.PoolableTargetChannelFactory.makeObject(PoolableTargetChannelFactory.java:61)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.wso2.carbon.transport.http.netty.sender.channel.pool.PoolableTargetChannelFactoryPerSrcHndlr.makeObject(PoolableTargetChannelFactoryPerSrcHndlr.java:40)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1181)
	at org.wso2.carbon.transport.http.netty.sender.channel.pool.ConnectionManager.borrowTargetChannel(ConnectionManager.java:168)
	at org.wso2.carbon.transport.http.netty.contractimpl.HttpClientConnectorImpl.send(HttpClientConnectorImpl.java:79)
	at org.ballerinalang.nativeimpl.actions.http.AbstractHTTPAction.executeNonBlockingAction(AbstractHTTPAction.java:187)
	at org.ballerinalang.nativeimpl.actions.http.Execute.execute(Execute.java:97)
	at org.ballerinalang.bre.bvm.BLangVM.invokeNativeAction(BLangVM.java:3067)
	at org.ballerinalang.bre.bvm.BLangVM.exec(BLangVM.java:551)
	at org.ballerinalang.bre.bvm.BLangVM.run(BLangVM.java:190)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.invokeResource(ServerConnectorMessageHandler.java:248)
	at org.ballerinalang.runtime.ServerConnectorMessageHandler.handleInbound(ServerConnectorMessageHandler.java:99)
	at org.ballerinalang.runtime.threadpool.RequestWorkerThread.run(RequestWorkerThread.java:35)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- <0x00000000f2c38fd8> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```
Testing artifacts can be found at : https://github.com/yasassri/ballerina-longrun

**Comment by shafreenAnfar** [comment]
This has been fixed in the snapshot.
