### ISSUE TITLE
[HTTP] Server becomes unresponsive and requests are failing 

### ISSUE THREAD

**Issue by yasassri** [ballerinalang/ballerina#3297]
**Steps**
1. Sent following set of requests with the given TPS.

  | Payload Size | TPS
-- | -- | --
HTTP Payloads | 1K | 15
  | 5K | 10
  | 10K | 7
  | 100K | 5
  | 500K | 2
  |   |  
  | Response Time |  
Slow Backends | 10s | 3
  | 7s | 4
  | 4s | 6

**Issue:** After sending few requests the server hangs and the connection is closed eventually.

In the thread-dump I could see the following,

```
"nioEventLoopGroup-3-8" #20 prio=10 os_prio=0 tid=0x00007f0638023800 nid=0x4190 waiting on condition [0x00007f06437f7000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000c079a7e8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at org.wso2.carbon.transport.http.netty.message.HTTPCarbonMessage.getHttpContent(HTTPCarbonMessage.java:87)
	at org.wso2.carbon.transport.http.netty.sender.channel.TargetChannel.writeContent(TargetChannel.java:162)
	at org.wso2.carbon.transport.http.netty.sender.channel.TargetChannelListener.operationComplete(TargetChannelListener.java:63)
	at org.wso2.carbon.transport.http.netty.sender.channel.TargetChannelListener.operationComplete(TargetChannelListener.java:34)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:479)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:82)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:306)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:630)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by shafreenAnfar** [comment]
This is fixed in the snapshot. We've done many load-tests and none of the failed. Hence closing the issue.
