### ISSUE TITLE
Observed Java stacktraces 

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/ballerina#3534]
To receive an Object type message via JMS server connector, it is required to put the receiving Class in Ballerina classpath (in <ballerina_home/jre/lib). If the user misses to include it in the class path, upon receiving the object type message, following java stacktrace will be printed on the console.

```
ERROR | ID:dilini-Latitude-E6540-34567-1507614251588-1:1:1:1 Exception while processing message: ID:dilini-Latitude-E6540-40273-1507614301778-0:0:1:1:1

java.lang.RuntimeException: An error occurred while listening to messages

	at org.wso2.carbon.transport.jms.receiver.JMSMessageListener.onMessage(JMSMessageListener.java:74)

	at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1404)

	at org.apache.activemq.ActiveMQMessageConsumer.iterate(ActiveMQMessageConsumer.java:1575)

	at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:191)

	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)

	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)

	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

	at java.lang.Thread.run(Thread.java:745)

Caused by: org.wso2.carbon.transport.jms.exception.JMSConnectorException: Error while getting the message from jms provider.

	at org.wso2.carbon.transport.jms.receiver.JMSMessageHandler.handle(JMSMessageHandler.java:111)

	at org.wso2.carbon.transport.jms.receiver.JMSMessageListener.onMessage(JMSMessageListener.java:72)

	... 8 more

Caused by: org.wso2.carbon.transport.jms.exception.JMSConnectorException: Error while changing the jms message to carbon message

	at org.wso2.carbon.transport.jms.utils.JMSUtils.createJMSCarbonMessage(JMSUtils.java:171)

	at org.wso2.carbon.transport.jms.receiver.JMSMessageHandler.handle(JMSMessageHandler.java:78)

	... 9 more

Caused by: javax.jms.JMSException: Failed to build body from content. Serializable class not available to broker. Reason: java.lang.ClassNotFoundException: org.ballerinalang.sample.jms.client.Person

	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36)

	at org.apache.activemq.command.ActiveMQObjectMessage.getObject(ActiveMQObjectMessage.java:213)

	at org.wso2.carbon.transport.jms.utils.JMSUtils.createJMSCarbonMessage(JMSUtils.java:124)

	... 10 more

Caused by: java.lang.ClassNotFoundException: org.ballerinalang.sample.jms.client.Person

	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)

	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)

	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

	at java.lang.Class.forName0(Native Method)

	at java.lang.Class.forName(Class.java:348)

	at org.apache.activemq.util.ClassLoadingAwareObjectInputStream.load(ClassLoadingAwareObjectInputStream.java:142)

	at org.apache.activemq.util.ClassLoadingAwareObjectInputStream.resolveClass(ClassLoadingAwareObjectInputStream.java:56)

	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)

	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)

	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)

	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)

	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)

	at org.apache.activemq.command.ActiveMQObjectMessage.getObject(ActiveMQObjectMessage.java:211)

	... 11 more
```

**Comment by SupunS** [comment]
This will tracked in: https://github.com/ballerinalang/connector-jms/issues/1
