### ISSUE TITLE
Java stacktrace printed on console

### ISSUE THREAD

**Issue by dilini-muthumala** [ballerinalang/ballerina#3535]
Scenario tested: receiving an object message via JMS (broker: ActiveMQ v5.15.1)

ActiveMQ v5.15.1 requires org.apache.activemq.SERIALIZABLE_PACKAGES environment variable to be set on Ballerina side [1].

If the user misses to do that, he will end up seeing a Java stacktrace as below:

```
ERROR | ID:dilini-Latitude-E6540-52700-1507616784837-1:587:1:1 Exception while processing message: ID:dilini-Latitude-E6540-34118-1507614970539-0:0:1:1:1
java.lang.RuntimeException: An error occurred while listening to messages
	at org.wso2.carbon.transport.jms.receiver.JMSMessageListener.onMessage(JMSMessageListener.java:74)
	at org.apache.activemq.ActiveMQMessageConsumer.dispatch(ActiveMQMessageConsumer.java:1404)
	at org.apache.activemq.ActiveMQSessionExecutor.dispatch(ActiveMQSessionExecutor.java:131)
	at org.apache.activemq.ActiveMQSessionExecutor.iterate(ActiveMQSessionExecutor.java:202)
	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.wso2.carbon.transport.jms.exception.JMSConnectorException: Error while getting the message from jms provider.
	at org.wso2.carbon.transport.jms.receiver.JMSMessageHandler.handle(JMSMessageHandler.java:111)
	at org.wso2.carbon.transport.jms.receiver.JMSMessageListener.onMessage(JMSMessageListener.java:72)
	... 8 more
Caused by: org.wso2.carbon.transport.jms.exception.JMSConnectorException: Error while changing the jms message to carbon message
	at org.wso2.carbon.transport.jms.utils.JMSUtils.createJMSCarbonMessage(JMSUtils.java:171)
	at org.wso2.carbon.transport.jms.receiver.JMSMessageHandler.handle(JMSMessageHandler.java:78)
	... 9 more
Caused by: javax.jms.JMSException: Failed to build body from content. Serializable class not available to broker. Reason: java.lang.ClassNotFoundException: Forbidden class org.ballerinalang.sample.jms.client.Person! This class is not trusted to be serialized as ObjectMessage payload. Please take a look at http://activemq.apache.org/objectmessage.html for more information on how to configure trusted classes.
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:36)
	at org.apache.activemq.command.ActiveMQObjectMessage.getObject(ActiveMQObjectMessage.java:213)
	at org.wso2.carbon.transport.jms.utils.JMSUtils.createJMSCarbonMessage(JMSUtils.java:124)
	... 10 more
Caused by: java.lang.ClassNotFoundException: Forbidden class org.ballerinalang.sample.jms.client.Person! This class is not trusted to be serialized as ObjectMessage payload. Please take a look at http://activemq.apache.org/objectmessage.html for more information on how to configure trusted classes.
	at org.apache.activemq.util.ClassLoadingAwareObjectInputStream.checkSecurity(ClassLoadingAwareObjectInputStream.java:112)
	at org.apache.activemq.util.ClassLoadingAwareObjectInputStream.resolveClass(ClassLoadingAwareObjectInputStream.java:57)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.activemq.command.ActiveMQObjectMessage.getObject(ActiveMQObjectMessage.java:211)
	... 11 more
```

[1] http://activemq.apache.org/objectmessage.html

**Comment by SupunS** [comment]
This will be tracked in: https://github.com/ballerinalang/connector-jms/issues/2
