### ISSUE TITLE
IndexOutOfBoundsException for mulit-return.

### ISSUE THREAD

**Issue by manuranga** [ballerinalang/ballerina#3692]
```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.handleAssignNodeWithVar(SemanticAnalyzer.java:972)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.SemanticAnalyzer.visit(SemanticAnalyzer.java:538)
	
```
for following input
```
function db_checkAndinsertUser(){
        var rs, _ = (User) dataStruct;
}
```

**Comment by hasithaa** [comment]
This is fixed in 0.94 release.
