### ISSUE TITLE
Following Program fails with Enum support. 

### ISSUE THREAD

**Issue by hasithaa** [ballerinalang/ballerina#3891]
enum state {
    foo,
    bar
}

function main(string[] arg) {
    state x = state;
    print(x);
}

This results. `ballerina: internal error occurred`

Actual stack trace. 
```
Exception in thread "main" java.lang.NullPointerException
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:509)
	at org.wso2.ballerinalang.compiler.tree.expressions.BLangSimpleVarRef.accept(BLangSimpleVarRef.java:59)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteExpr(Desugar.java:925)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:273)
	at org.wso2.ballerinalang.compiler.tree.BLangVariable.accept(BLangVariable.java:81)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:907)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:305)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangVariableDef.accept(BLangVariableDef.java:42)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:907)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:939)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewriteStmt(Desugar.java:949)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:299)
	at org.wso2.ballerinalang.compiler.tree.statements.BLangBlockStmt.accept(BLangBlockStmt.java:53)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:907)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:939)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:202)
	at org.wso2.ballerinalang.compiler.tree.BLangFunction.accept(BLangFunction.java:41)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:907)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:956)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.visit(Desugar.java:182)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:145)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.rewrite(Desugar.java:907)
	at org.wso2.ballerinalang.compiler.desugar.Desugar.perform(Desugar.java:168)
	at org.wso2.ballerinalang.compiler.Compiler.desugar(Compiler.java:162)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:106)
	at org.ballerinalang.examples.BTester.main(BTester.java:34)
```

**Comment by hasithaa** [comment]
This is fixed in 0.95
